name = "bizwiz3/import"
version = "0.1.0"
description = "A lightweight alternative to Luau's native require for cases where path traversal becomes a maintainability problem."
license = "MIT"
authors = ["BizWiz3 (https://github.com/BizWiz3)"]
repository = "https://github.com/BizWiz3/import"
private = false
includes = ["pesde.toml", "README.md", "LICENSE", "src/**/*.luau"]

[target]
environment = "luau"
lib = "src/init.luau"
